contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
staticdir = "static"
baseurl = ""
canonifyurls = true
theme = "minimesos"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "minimesos.org styles"
  author = ""
