contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "http://minimesos.org/"
canonifyurls = true
theme = "minimesos"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "minimesos.org"
  author = ""