name = "minimesos.org"
license = "MIT"
licenselink = ""
description = ""
homepage = "http://minimesos.org/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Container Solutions"
  homepage = "http://container-solutions.com/"
